services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: aperture
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
  php-symfony:
    container_name: php-symfony
    build:
      context: ./.docker/php-symfony
    depends_on:
      - postgres
    links:
      - postgres
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/GSB-Medecins
